#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f cpu.vcd

# run Verilator to translate Verilog into C++, ncluding C++ testbench
verilator -Wall --cc --trace cpu.sv --exe cpu_tb.cpp

# build C++ project via male automatically generated by Verilator
make -j -C obj_dir/ -f Vcpu.mk Vcpu

# run executable sim file
obj_dir/Vcpu
