#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f green.vcd

# run Verilator to translate Verilog into C++, ncluding C++ testbench
verilator -Wall --cc --trace green_top.sv --exe green_tb.cpp

# build C++ project via male automatically generated by Verilator
make -j -C obj_dir/ -f Vgreen_top.mk Vgreen_top

# run executable sim file
obj_dir/Vgreen_top
